In [2]:
from sqlalchemy import create_engine
import pandas as pd
import pyodbc

In [3]:
# using SQLalchemy 


database = 'hackathon_danone'
username = 'hack08'
password = 'TEdNNMW3g4!'
driver= '/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.3.so.1.1'
server = '192.168.250.3'

my_engine = create_engine(f'mssql+pyodbc://{username}:{password}@192.168.250.3:1433/{database}?driver={driver}', fast_executemany=True)


def db_sql(sql):
    cnxn = pyodbc.connect(f'DRIVER={driver};PORT=1433;SERVER={server};DATABASE={database};UID={username};PWD={password}')
    data = pd.read_sql(sql,cnxn)
    cnxn.close()    
    return data

In [16]:
show_all_tables_sql = f"""
    SELECT table_name FROM information_schema.tables;
    """
get_recipe_1_processing_details_slurry_sql = f"""
    SELECT * FROM recipe_1_processing_details_slurry
    """
recipe_1_processing_details_bigbag_sql = f"""
    SELECT * FROM recipe_1_processing_details_bigbag
    """
recipe_1_processing_details_dd_sql = f"""
    SELECT * FROM recipe_1_processing_details_dd
    """
recipe_1_out_test_during_production_sql = f"""
    SELECT * FROM recipe_1_out_test_during_production
    """
recipe_1_out_test_during_production_sql = f"""
    SELECT * FROM recipe_1_out_test_during_production
    """

In [17]:
show_all_tables = db_sql(show_all_tables_sql)
print(show_all_tables)

                               table_name
0      recipe_1_processing_details_slurry
1      recipe_1_processing_details_bigbag
2          recipe_1_processing_details_dd
3     recipe_1_out_test_during_production
4   recipe_1_out_semi_finished_production
5                              Walec DD02
6                              Walec DD05
7                              Walec DD08
8                    results_test_dataset
9                 recipe_0_orders_details
10             recipe_0_raw_material_used
11               recipe_0_raw_material_in
12     recipe_0_processing_details_slurry
13     recipe_0_processing_details_bigbag
14         recipe_0_processing_details_dd
15    recipe_0_out_test_during_production
16  recipe_0_out_semi_finished_production
17                recipe_1_orders_details
18             recipe_1_raw_material_used
19               recipe_1_raw_material_in

In [18]:
show_all_tables = db_sql(get_recipe_1_processing_details_slurry_sql)
print(show_all_tables)

    orders_details_id  slurry_process_order slurry_line   slurry_start_time  \
0                   0                     1        SL 2 2018-03-21 06:00:00
1                   0                     2        SL 2 2018-03-21 14:00:00
2                   0                     3        SL 2 2018-03-21 16:20:00
3                   0                     4        SL 2 2018-03-21 22:00:00
4                   1                     1        SL 2 2018-03-22 06:00:00
5                   1                     2        SL 2 2018-03-22 14:00:00
6                   1                     3        SL 2 2018-03-22 22:00:00
7                   2                     1        SL 2 2018-03-23 14:00:00
8                   3                     1        SL 2 2018-03-26 18:15:00
9                   3                     2        SL 2 2018-03-26 18:25:00
10                  3                     3        SL 2 2018-03-26 22:00:00
11                  3                     4        SL 2 2018-03-27 06:00:00
12                  4                     1        SL 3 2018-04-03 19:25:00
13                  4                     2        SL 3 2018-04-03 22:00:00
14                  4                     3        SL 3 2018-04-04 06:00:00
15                  5                     1        SL 3 2018-04-04 22:00:00
16                  5                     2        SL 3 2018-04-04 14:00:00
17                  5                     3        SL 2 2018-04-05 09:00:00
18                  5                     4        SL 2 2018-04-05 14:00:00
19                  6                     1        SL 2 2018-12-04 06:00:00
20                  6                     2        SL 2 2018-12-04 22:40:00
21                  6                     3        SL 2 2018-12-04 14:00:00
22                  7                     1        SL 3 2018-04-17 14:00:00
23                  7                     2        SL 3 2018-04-17 22:00:00
24                  7                     3        SL 3 2018-04-18 06:00:00
25                  8                     1        SL 3 2018-04-18 14:00:00
26                  8                     2        SL 3 2018-04-18 22:00:00
27                  8                     3         SL2 2018-04-19 00:55:00
28                  8                     4         SL2 2018-04-19 06:00:00
29                  8                     5         SL2 2018-04-19 14:00:00
..                ...                   ...         ...                 ...
41                 13                     1        SL 2 2018-05-14 15:15:00
42                 13                     2        SL 2 2018-05-14 22:00:00
43                 13                     3        SL 2 2018-05-15 06:00:00
44                 14                     1        SL 3 2018-05-14 16:25:00
45                 14                     2        SL 3 2018-05-14 22:00:00
46                 14                     3        SL 3 2018-05-15 06:00:00
47                 15                     1        SL 3 2018-05-15 14:00:00
48                 15                     2        SL 3 2018-05-15 22:00:00
49                 15                     3        SL 3 2018-05-16 06:00:00
50                 16                     1        SL 2 2018-05-15 14:00:00
51                 16                     2        SL 2 2018-05-15 22:00:00
52                 16                     3        SL 2 2018-05-15 06:00:00
53                 17                     1        SL 3 2018-05-16 14:00:00
54                 17                     2        SL 3 2018-05-16 18:00:00
55                 17                     3        SL 3 2018-05-16 18:10:00
56                 17                     4        SL 3 2018-05-16 18:30:00
57                 17                     5        SL 3 2018-05-16 22:00:00
58                 17                     6        SL 3 2018-05-17 06:00:00
59                 18                     1        SL 2 2018-05-16 14:00:00
60                 18                     2        SL 2 2018-05-16 16:15:00
61                 18                     3        SL 2 2018-05-16 16:25:00
62                 18                     4        SL 2 2018-05-16 22:00:00
63                 19                     1        SL 2 2018-05-21 15:20:00
64                 19                     2        SL 2 2018-05-21 22:00:00
65                 19                     3        SL 2 2018-05-22 06:00:00
66                 20                     1        SL 2 2018-05-22 14:00:00
67                 20                     2        SL 2 2018-05-22 22:00:00
68                 21                     1        SL 3 2018-05-29 06:00:00
69                 21                     2        SL 2 2018-05-29 14:00:00
70                 21                     3        SL 2 2018-05-29 22:00:00

    water_pct  water_correction
0        0.66             -40.0
1        0.66             -40.0
2        0.66             -40.0
3        0.66             -40.0
4        0.66             -40.0
5        0.66             -40.0
6        0.66             -40.0
7        0.66             -40.0
8        0.66             -75.0
9        0.66             -70.0
10       0.66             -70.0
11       0.66             -50.0
12       0.66             -50.0
13       0.66             -40.0
14       0.66             -40.0
15       0.66             -40.0
16       0.66             -40.0
17       0.66             -40.0
18       0.66             -40.0
19       0.66             -50.0
20       0.66             -50.0
21       0.66             -50.0
22       0.66             -40.0
23       0.66             -40.0
24       0.66             -40.0
25       0.66             -40.0
26       0.66             -40.0
27       0.66             -50.0
28       0.66             -50.0
29       0.66             -50.0
..        ...               ...
41       0.66             -50.0
42       0.66             -40.0
43       0.66             -40.0
44       0.66             -50.0
45       0.66             -40.0
46       0.66             -40.0
47       0.66             -40.0
48       0.66             -40.0
49       0.66             -40.0
50       0.66             -40.0
51       0.66             -40.0
52       0.66             -40.0
53       0.66             -40.0
54       0.66             -50.0
55       0.66             -40.0
56       0.66             -50.0
57       0.66             -40.0
58       0.66             -40.0
59       0.66             -40.0
60       0.66             -50.0
61       0.66             -40.0
62       0.66             -40.0
63       0.66             -40.0
64       0.66             -40.0
65       0.66             -40.0
66       0.66             -40.0
67       0.66             -40.0
68       0.66             -40.0
69       0.66             -40.0
70       0.66             -40.0

[71 rows x 6 columns]

In [11]:
get_recipe_1_processing_details_slurry = db_sql(get_recipe_1_processing_details_slurry)

In [12]:
print(Data)

    orders_details_id  slurry_process_order slurry_line   slurry_start_time  \
0                   0                     1        SL 2 2018-03-21 06:00:00
1                   0                     2        SL 2 2018-03-21 14:00:00
2                   0                     3        SL 2 2018-03-21 16:20:00
3                   0                     4        SL 2 2018-03-21 22:00:00
4                   1                     1        SL 2 2018-03-22 06:00:00
5                   1                     2        SL 2 2018-03-22 14:00:00
6                   1                     3        SL 2 2018-03-22 22:00:00
7                   2                     1        SL 2 2018-03-23 14:00:00
8                   3                     1        SL 2 2018-03-26 18:15:00
9                   3                     2        SL 2 2018-03-26 18:25:00
10                  3                     3        SL 2 2018-03-26 22:00:00
11                  3                     4        SL 2 2018-03-27 06:00:00
12                  4                     1        SL 3 2018-04-03 19:25:00
13                  4                     2        SL 3 2018-04-03 22:00:00
14                  4                     3        SL 3 2018-04-04 06:00:00
15                  5                     1        SL 3 2018-04-04 22:00:00
16                  5                     2        SL 3 2018-04-04 14:00:00
17                  5                     3        SL 2 2018-04-05 09:00:00
18                  5                     4        SL 2 2018-04-05 14:00:00
19                  6                     1        SL 2 2018-12-04 06:00:00
20                  6                     2        SL 2 2018-12-04 22:40:00
21                  6                     3        SL 2 2018-12-04 14:00:00
22                  7                     1        SL 3 2018-04-17 14:00:00
23                  7                     2        SL 3 2018-04-17 22:00:00
24                  7                     3        SL 3 2018-04-18 06:00:00
25                  8                     1        SL 3 2018-04-18 14:00:00
26                  8                     2        SL 3 2018-04-18 22:00:00
27                  8                     3         SL2 2018-04-19 00:55:00
28                  8                     4         SL2 2018-04-19 06:00:00
29                  8                     5         SL2 2018-04-19 14:00:00
..                ...                   ...         ...                 ...
41                 13                     1        SL 2 2018-05-14 15:15:00
42                 13                     2        SL 2 2018-05-14 22:00:00
43                 13                     3        SL 2 2018-05-15 06:00:00
44                 14                     1        SL 3 2018-05-14 16:25:00
45                 14                     2        SL 3 2018-05-14 22:00:00
46                 14                     3        SL 3 2018-05-15 06:00:00
47                 15                     1        SL 3 2018-05-15 14:00:00
48                 15                     2        SL 3 2018-05-15 22:00:00
49                 15                     3        SL 3 2018-05-16 06:00:00
50                 16                     1        SL 2 2018-05-15 14:00:00
51                 16                     2        SL 2 2018-05-15 22:00:00
52                 16                     3        SL 2 2018-05-15 06:00:00
53                 17                     1        SL 3 2018-05-16 14:00:00
54                 17                     2        SL 3 2018-05-16 18:00:00
55                 17                     3        SL 3 2018-05-16 18:10:00
56                 17                     4        SL 3 2018-05-16 18:30:00
57                 17                     5        SL 3 2018-05-16 22:00:00
58                 17                     6        SL 3 2018-05-17 06:00:00
59                 18                     1        SL 2 2018-05-16 14:00:00
60                 18                     2        SL 2 2018-05-16 16:15:00
61                 18                     3        SL 2 2018-05-16 16:25:00
62                 18                     4        SL 2 2018-05-16 22:00:00
63                 19                     1        SL 2 2018-05-21 15:20:00
64                 19                     2        SL 2 2018-05-21 22:00:00
65                 19                     3        SL 2 2018-05-22 06:00:00
66                 20                     1        SL 2 2018-05-22 14:00:00
67                 20                     2        SL 2 2018-05-22 22:00:00
68                 21                     1        SL 3 2018-05-29 06:00:00
69                 21                     2        SL 2 2018-05-29 14:00:00
70                 21                     3        SL 2 2018-05-29 22:00:00

    water_pct  water_correction
0        0.66             -40.0
1        0.66             -40.0
2        0.66             -40.0
3        0.66             -40.0
4        0.66             -40.0
5        0.66             -40.0
6        0.66             -40.0
7        0.66             -40.0
8        0.66             -75.0
9        0.66             -70.0
10       0.66             -70.0
11       0.66             -50.0
12       0.66             -50.0
13       0.66             -40.0
14       0.66             -40.0
15       0.66             -40.0
16       0.66             -40.0
17       0.66             -40.0
18       0.66             -40.0
19       0.66             -50.0
20       0.66             -50.0
21       0.66             -50.0
22       0.66             -40.0
23       0.66             -40.0
24       0.66             -40.0
25       0.66             -40.0
26       0.66             -40.0
27       0.66             -50.0
28       0.66             -50.0
29       0.66             -50.0
..        ...               ...
41       0.66             -50.0
42       0.66             -40.0
43       0.66             -40.0
44       0.66             -50.0
45       0.66             -40.0
46       0.66             -40.0
47       0.66             -40.0
48       0.66             -40.0
49       0.66             -40.0
50       0.66             -40.0
51       0.66             -40.0
52       0.66             -40.0
53       0.66             -40.0
54       0.66             -50.0
55       0.66             -40.0
56       0.66             -50.0
57       0.66             -40.0
58       0.66             -40.0
59       0.66             -40.0
60       0.66             -50.0
61       0.66             -40.0
62       0.66             -40.0
63       0.66             -40.0
64       0.66             -40.0
65       0.66             -40.0
66       0.66             -40.0
67       0.66             -40.0
68       0.66             -40.0
69       0.66             -40.0
70       0.66             -40.0

[71 rows x 6 columns]

In [7]:
#recipe_1_processing_details_slurry_df = pd.read_sql_table('recipe_1_processing_details_slurry', my_engine, schema=None, index_col=None, coerce_float=True, parse_dates=None, columns=None, chunksize=None)
#recipe_1_processing_details_bigbag_df = pd.read_sql_table('recipe_1_processing_details_bigbag', my_engine, schema=None, index_col=None, coerce_float=True, parse_dates=None, columns=None, chunksize=None)
#recipe_1_processing_details_dd_df = pd.read_sql_table('recipe_1_processing_details_dd', my_engine, schema=None, index_col=None, coerce_float=True, parse_dates=None, columns=None, chunksize=None)
#recipe_1_out_test_during_production_df = pd.read_sql_table('recipe_1_out_test_during_production', my_engine, schema=None, index_col=None, coerce_float=True, parse_dates=None, columns=None, chunksize=None)
#recipe_1_out_semi_finished_production_df = pd.read_sql_table('recipe_1_out_semi_finished_production', my_engine, schema=None, index_col=None, coerce_float=True, parse_dates=None, columns=None, chunksize=None)
Walec_DD02_df = pd.read_sql_table('Walec DD02', my_engine, schema=None, index_col=None, coerce_float=True, parse_dates=None, columns=None, chunksize=None)
Walec_DD05_df = pd.read_sql_table('Walec DD05', my_engine, schema=None, index_col=None, coerce_float=True, parse_dates=None, columns=None, chunksize=None)
Walec_DD08_df = pd.read_sql_table('Walec DD08', my_engine, schema=None, index_col=None, coerce_float=True, parse_dates=None, columns=None, chunksize=None)
#results_test_dataset_df = pd.read_sql_table('results_test_dataset', my_engine, schema=None, index_col=None, coerce_float=True, parse_dates=None, columns=None, chunksize=None)
recipe_0_orders_details_df = pd.read_sql_table('recipe_0_orders_details', my_engine, schema=None, index_col=None, coerce_float=True, parse_dates=None, columns=None, chunksize=None)
recipe_0_raw_material_used_df = pd.read_sql_table('recipe_0_raw_material_used', my_engine, schema=None, index_col=None, coerce_float=True, parse_dates=None, columns=None, chunksize=None)
recipe_0_raw_material_in_df = pd.read_sql_table('recipe_0_raw_material_in', my_engine, schema=None, index_col=None, coerce_float=True, parse_dates=None, columns=None, chunksize=None)
recipe_0_processing_details_slurry_df = pd.read_sql_table('recipe_0_processing_details_slurry', my_engine, schema=None, index_col=None, coerce_float=True, parse_dates=None, columns=None, chunksize=None)
recipe_0_processing_details_bigbag_df = pd.read_sql_table('recipe_0_processing_details_bigbag', my_engine, schema=None, index_col=None, coerce_float=True, parse_dates=None, columns=None, chunksize=None)
recipe_0_processing_details_dd_df = pd.read_sql_table('recipe_0_processing_details_dd', my_engine, schema=None, index_col=None, coerce_float=True, parse_dates=None, columns=None, chunksize=None)
recipe_0_out_test_during_production_df = pd.read_sql_table('recipe_0_out_test_during_production', my_engine, schema=None, index_col=None, coerce_float=True, parse_dates=None, columns=None, chunksize=None)
recipe_0_out_semi_finished_production_df = pd.read_sql_table('recipe_0_out_semi_finished_production', my_engine, schema=None, index_col=None, coerce_float=True, parse_dates=None, columns=None, chunksize=None)
#recipe_1_orders_details_df = pd.read_sql_table('recipe_1_orders_details', my_engine, schema=None, index_col=None, coerce_float=True, parse_dates=None, columns=None, chunksize=None)
#recipe_1_raw_material_used_df = pd.read_sql_table('recipe_1_raw_material_used', my_engine, schema=None, index_col=None, coerce_float=True, parse_dates=None, columns=None, chunksize=None)
#recipe_1_raw_material_in_df = pd.read_sql_table('recipe_1_raw_material_in', my_engine, schema=None, index_col=None, coerce_float=True, parse_dates=None, columns=None, chunksize=None)

In [ ]:
recipe_0_orders_details
recipe_0_raw_material_in
recipe_0_raw_material_used
recipe_0_processing_details_slurry
recipe_0_processing_details_bigbag
recipe_0_processing_details_dd
recipe_0_out_test_during_production
recipe_0_out_semi_finished_production

In [27]:
list(Walec_DD05_df)

['timestamp',
 'steam_pressure_at_the_inlet_of_regulation_unit',
 'product_temperature_at_the_outlet_of_JetCooker',
 'steam_pressure_at_DD_inlet',
 'condensate_temperature_at_DD_outlet',
 'setpoint_of_product_temperature',
 'product_temperature_at_the_outlet_of_product',
 'steam_pressure_at_the_outlet_of_regulation_unit',
 'product_temperature_at_the_inlet',
 'setpoint_of_steam_pressure_at_the_DD_inlet']

In [14]:
list(Walec_DD02_df)

['orders_details_id',
 'bigbag_number',
 'bigbag_filling_time_end',
 'bigbag_filling_duration',
 'bigbag_weight',
 'efficiency',
 'class']

In [43]:
list(Walec_DD05_df)

['timestamp',
 'steam_pressure_at_the_inlet_of_regulation_unit',
 'product_temperature_at_the_outlet_of_JetCooker',
 'steam_pressure_at_DD_inlet',
 'condensate_temperature_at_DD_outlet',
 'setpoint_of_product_temperature',
 'product_temperature_at_the_outlet_of_product',
 'steam_pressure_at_the_outlet_of_regulation_unit',
 'product_temperature_at_the_inlet',
 'setpoint_of_steam_pressure_at_the_DD_inlet']

In [16]:
list(Walec_DD08_df)

['timestamp',
 'steam_pressure_at_the_inlet_of_regulation_unit',
 'product_temperature_at_the_outlet_of_JetCooker',
 'setpoint_of_steam_pressure_at_the_DD_inlet',
 'condensate_temperature_at_DD_outlet',
 'product_temperature_at_the_inlet',
 'setpoint_of_product_temperature',
 'product_at_the_outlet_of_JetCooker',
 'steam_pressure_at_the_inlet_of_JetCooker',
 'steam_pressure_at_the_outlet_of_regulation_unit',
 'product_temperature_at_the_outlet_of_product']

In [44]:
list(recipe_0_orders_details_df)

['id',
 'line_dd',
 'production_order',
 'process_order_sap',
 'material_code',
 'recipe',
 'activation_date',
 'closing_date',
 'data_split']

In [42]:
list(recipe_0_raw_material_used_df)

['id', 'material_code_2', 'process_order_sap3', 'usage_pct']

In [41]:
list(recipe_0_raw_material_in_df)

['id',
 'process_order_sap3',
 'fat_pct',
 'particles_grp1',
 'particles_grp2',
 'particles_grp3',
 'moisture']

In [20]:
list(recipe_0_processing_details_slurry_df)

['orders_details_id',
 'slurry_process_order',
 'slurry_line',
 'slurry_start_time',
 'water_pct',
 'water_correction']

In [21]:
list(recipe_0_processing_details_bigbag_df)

['orders_details_id',
 'bigbag_number',
 'bigbag_filling_time_end',
 'sifter_speed_nominal_pct']

In [40]:
list(recipe_0_processing_details_dd_df.orders_details_id)

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 23,
 23,
 23,
 23,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 26,
 26,
 26,
 26,
 26,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30]

In [23]:
list(recipe_0_out_test_during_production_df)

['orders_details_id',
 'line_dd',
 'process_order',
 'testing_time',
 'moisture',
 'bulk_density']

In [24]:
list(recipe_0_out_semi_finished_production_df)

['orders_details_id',
 'bigbag_number',
 'bigbag_filling_time_end',
 'bigbag_filling_duration',
 'bigbag_weight',
 'efficiency',
 'class']

In [29]:
recipe_0_out_test_during_production_df

,orders_details_id,testing_time,steam_preasure,dd_speed,temp_out
0,1,2018-06-04 17:30:00.000,8.0,7.0,118.0
1,1,2018-06-04 18:30:00.000,8.0,7.5,118.0
2,1,2018-06-04 19:30:00.000,8.0,7.5,118.0
3,1,2018-06-04 20:30:00.000,8.0,7.5,118.0
4,1,2018-06-04 21:30:00.000,8.0,7.5,118.0
5,1,2018-06-04 22:30:00.000,8.0,8.0,114.0
6,1,2018-06-04 23:30:00.000,8.0,8.5,113.0
7,1,2018-06-05 00:30:00.000,8.2,8.5,112.0
8,1,2018-06-05 01:30:00.000,8.2,8.5,112.0
9,1,2018-06-05 02:30:00.000,8.2,8.5,112.0
10,1,2018-06-05 03:30:00.000,8.2,8.5,113.0
11,1,2018-06-05 04:30:00.000,8.2,9.0,113.0
12,1,2018-06-05 05:30:00.000,8.2,9.0,112.0
13,1,2018-06-05 06:30:00.000,8.2,9.0,112.0
14,1,2018-06-05 08:30:00.000,8.2,10.0,112.0
15,1,2018-06-05 09:30:00.000,8.2,8.0,112.0
16,1,2018-06-05 10:30:00.000,8.2,10.5,112.0
17,1,2018-06-05 11:30:00.000,8.2,10.0,112.0
18,1,2018-06-05 12:30:00.000,8.2,9.5,112.0
19,1,2018-06-05 13:30:00.000,7.5,9.5,112.0
20,3,2018-06-06 14:30:00.000,8.0,9.0,113.0
21,3,2018-06-06 15:30:00.000,8.0,9.0,113.0
22,3,2018-06-06 16:30:00.007,8.0,9.0,113.0
23,3,2018-06-06 17:30:00.010,7.8,9.0,114.0
24,3,2018-06-06 18:30:00.017,7.8,9.0,114.0
25,3,2018-06-06 19:30:00.020,7.8,9.0,114.0
26,3,2018-06-06 20:30:00.027,7.8,9.0,114.0
27,3,2018-06-06 21:30:00.030,7.8,9.0,114.0
28,3,2018-06-06 22:30:00.037,7.8,9.0,114.0
29,3,2018-06-06 23:30:00.040,7.8,9.0,114.0
...,...,...,...,...,...
496,29,2019-02-18 14:30:00.000,5.8,8.0,111.0
497,29,2019-02-18 15:30:00.000,5.8,8.0,111.0
498,29,2019-02-18 16:30:00.000,5.8,8.0,111.0
499,29,2019-02-18 17:30:00.000,5.8,8.0,111.0
500,29,2019-02-18 18:30:00.000,5.9,8.0,111.0
501,29,2019-02-18 19:30:00.000,5.9,8.0,112.0
502,29,2019-02-18 20:30:00.000,5.9,8.0,112.0
503,29,2019-02-18 21:30:00.000,5.9,8.0,111.0
504,29,2019-02-18 22:30:00.000,5.9,8.0,111.0
505,29,2019-02-18 23:30:00.000,5.9,8.0,111.0
506,29,2019-02-19 00:30:00.000,5.9,8.0,111.0
507,29,2019-02-19 01:30:00.000,5.9,8.0,111.0
508,29,2019-02-19 02:30:00.000,5.9,8.0,111.0
509,29,2019-02-19 03:30:00.000,5.9,8.0,111.0
510,29,2019-02-19 04:30:00.000,5.9,8.0,111.0
511,29,2019-02-19 05:30:00.000,5.9,8.0,111.0
512,30,2019-03-01 06:30:00.000,5.9,8.0,110.0
513,30,2019-03-01 07:30:00.000,5.9,8.0,110.0
514,30,2019-03-01 08:30:00.000,6.1,8.5,110.0
515,30,2019-03-01 09:30:00.000,6.4,8.5,110.0
516,30,2019-03-01 10:30:00.000,6.4,8.5,111.0
517,30,2019-03-01 11:30:00.000,6.4,8.5,110.0
518,30,2019-03-01 12:30:00.000,6.4,8.0,112.0
519,30,2019-03-01 13:30:00.000,6.4,8.0,112.0
520,30,2019-03-01 14:30:00.000,6.2,8.0,112.0
521,30,2019-03-01 15:30:00.000,6.3,8.3,112.0
522,30,2019-03-01 16:30:00.000,6.5,8.3,112.0
523,30,2019-03-01 17:30:00.000,6.5,8.3,111.0
524,30,2019-03-01 18:30:00.000,6.5,8.3,111.0
525,30,2019-03-01 19:30:00.000,6.5,8.3,111.0

In [36]:
recipe_0_processing_details_dd_df

,orders_details_id,testing_time,steam_preasure,dd_speed,temp_out
0,1,2018-06-04 17:30:00.000,8.0,7.0,118.0
1,1,2018-06-04 18:30:00.000,8.0,7.5,118.0
2,1,2018-06-04 19:30:00.000,8.0,7.5,118.0
3,1,2018-06-04 20:30:00.000,8.0,7.5,118.0
4,1,2018-06-04 21:30:00.000,8.0,7.5,118.0
5,1,2018-06-04 22:30:00.000,8.0,8.0,114.0
6,1,2018-06-04 23:30:00.000,8.0,8.5,113.0
7,1,2018-06-05 00:30:00.000,8.2,8.5,112.0
8,1,2018-06-05 01:30:00.000,8.2,8.5,112.0
9,1,2018-06-05 02:30:00.000,8.2,8.5,112.0
10,1,2018-06-05 03:30:00.000,8.2,8.5,113.0
11,1,2018-06-05 04:30:00.000,8.2,9.0,113.0
12,1,2018-06-05 05:30:00.000,8.2,9.0,112.0
13,1,2018-06-05 06:30:00.000,8.2,9.0,112.0
14,1,2018-06-05 08:30:00.000,8.2,10.0,112.0
15,1,2018-06-05 09:30:00.000,8.2,8.0,112.0
16,1,2018-06-05 10:30:00.000,8.2,10.5,112.0
17,1,2018-06-05 11:30:00.000,8.2,10.0,112.0
18,1,2018-06-05 12:30:00.000,8.2,9.5,112.0
19,1,2018-06-05 13:30:00.000,7.5,9.5,112.0
20,3,2018-06-06 14:30:00.000,8.0,9.0,113.0
21,3,2018-06-06 15:30:00.000,8.0,9.0,113.0
22,3,2018-06-06 16:30:00.007,8.0,9.0,113.0
23,3,2018-06-06 17:30:00.010,7.8,9.0,114.0
24,3,2018-06-06 18:30:00.017,7.8,9.0,114.0
25,3,2018-06-06 19:30:00.020,7.8,9.0,114.0
26,3,2018-06-06 20:30:00.027,7.8,9.0,114.0
27,3,2018-06-06 21:30:00.030,7.8,9.0,114.0
28,3,2018-06-06 22:30:00.037,7.8,9.0,114.0
29,3,2018-06-06 23:30:00.040,7.8,9.0,114.0
...,...,...,...,...,...
496,29,2019-02-18 14:30:00.000,5.8,8.0,111.0
497,29,2019-02-18 15:30:00.000,5.8,8.0,111.0
498,29,2019-02-18 16:30:00.000,5.8,8.0,111.0
499,29,2019-02-18 17:30:00.000,5.8,8.0,111.0
500,29,2019-02-18 18:30:00.000,5.9,8.0,111.0
501,29,2019-02-18 19:30:00.000,5.9,8.0,112.0
502,29,2019-02-18 20:30:00.000,5.9,8.0,112.0
503,29,2019-02-18 21:30:00.000,5.9,8.0,111.0
504,29,2019-02-18 22:30:00.000,5.9,8.0,111.0
505,29,2019-02-18 23:30:00.000,5.9,8.0,111.0
506,29,2019-02-19 00:30:00.000,5.9,8.0,111.0
507,29,2019-02-19 01:30:00.000,5.9,8.0,111.0
508,29,2019-02-19 02:30:00.000,5.9,8.0,111.0
509,29,2019-02-19 03:30:00.000,5.9,8.0,111.0
510,29,2019-02-19 04:30:00.000,5.9,8.0,111.0
511,29,2019-02-19 05:30:00.000,5.9,8.0,111.0
512,30,2019-03-01 06:30:00.000,5.9,8.0,110.0
513,30,2019-03-01 07:30:00.000,5.9,8.0,110.0
514,30,2019-03-01 08:30:00.000,6.1,8.5,110.0
515,30,2019-03-01 09:30:00.000,6.4,8.5,110.0
516,30,2019-03-01 10:30:00.000,6.4,8.5,111.0
517,30,2019-03-01 11:30:00.000,6.4,8.5,110.0
518,30,2019-03-01 12:30:00.000,6.4,8.0,112.0
519,30,2019-03-01 13:30:00.000,6.4,8.0,112.0
520,30,2019-03-01 14:30:00.000,6.2,8.0,112.0
521,30,2019-03-01 15:30:00.000,6.3,8.3,112.0
522,30,2019-03-01 16:30:00.000,6.5,8.3,112.0
523,30,2019-03-01 17:30:00.000,6.5,8.3,111.0
524,30,2019-03-01 18:30:00.000,6.5,8.3,111.0
525,30,2019-03-01 19:30:00.000,6.5,8.3,111.0

In [34]:
subset_recipe_0_processing_details_dd_df = recipe_0_processing_details_dd_df.loc[ : ,['steam_preasure', 'dd_speed'] ]

In [35]:
subset_recipe_0_processing_details_dd_df

     steam_preasure  dd_speed
0               8.0       7.0
1               8.0       7.5
2               8.0       7.5
3               8.0       7.5
4               8.0       7.5
5               8.0       8.0
6               8.0       8.5
7               8.2       8.5
8               8.2       8.5
9               8.2       8.5
10              8.2       8.5
11              8.2       9.0
12              8.2       9.0
13              8.2       9.0
14              8.2      10.0
15              8.2       8.0
16              8.2      10.5
17              8.2      10.0
18              8.2       9.5
19              7.5       9.5
20              8.0       9.0
21              8.0       9.0
22              8.0       9.0
23              7.8       9.0
24              7.8       9.0
25              7.8       9.0
26              7.8       9.0
27              7.8       9.0
28              7.8       9.0
29              7.8       9.0
..              ...       ...
496             5.8       8.0
497             5.8       8.0
498             5.8       8.0
499             5.8       8.0
500             5.9       8.0
501             5.9       8.0
502             5.9       8.0
503             5.9       8.0
504             5.9       8.0
505             5.9       8.0
506             5.9       8.0
507             5.9       8.0
508             5.9       8.0
509             5.9       8.0
510             5.9       8.0
511             5.9       8.0
512             5.9       8.0
513             5.9       8.0
514             6.1       8.5
515             6.4       8.5
516             6.4       8.5
517             6.4       8.5
518             6.4       8.0
519             6.4       8.0
520             6.2       8.0
521             6.3       8.3
522             6.5       8.3
523             6.5       8.3
524             6.5       8.3
525             6.5       8.3

[526 rows x 2 columns]